### ISSUE TITLE
Extension doesn't support Gnome Shell 3.24.3

### ISSUE THREAD

**Issue by yodatak** [andyholmes/gnome-shell-extension-mconnect#11]
With the release or with the meson compiled I got a invalid extention using gnome tweak extentions installation 
How can i give you more debug messages about this to fix it ?

**Comment by andyholmes** [comment]
@yodatak this may be related to issue #9, can you report your version of Gnome Shell (`gnome-shell --version`) and GJS too, if possible?

**Comment by yodatak** [comment]
There is go 👍 
╰─ gnome-shell --version
GNOME Shell 3.24.3
╰─ gjs --version
gjs 1.48.6
On fedora 26 64bit

**Comment by andyholmes** [comment]
Ah, I didn't realize 3.24.3 had been released yet. This will be fixed in v6, for now you can just edit 'metadata.json' and add '3.24.3' to the 'shell-version' variable. Thanks for reporting!
