### ISSUE TITLE
Strange version numbers

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-mconnect#13]
Is it common for GNOME extensions to version their releases with natural numbers (1, 2, 3, 4, 5, …)?

Can't you follow [semantic versioning](semver.org) using 0.1, 0.2, … for the beta phase at least and begin with v1.0 when it is ready?

**Comment by andyholmes** [comment]
Yes, it's become common practice for extensions to use natural numbering. In fact, the official extension website enforces it and automatically modifies `metadata.json` to conform if you try to use a different scheme. Not realizing that in the beginning caused a bit of confusion with some users thinking v1 on the website was older different than v2 in the Release page.
