### ISSUE TITLE
When trying to browse files disk usage analyzer pops up instead of nautilus

### ISSUE THREAD

**Issue by dal00** [andyholmes/gnome-shell-extension-mconnect#15]
When trying to browse files disk usage analyzer pops up instead of nautilus.

**Comment by andyholmes** [comment]
@dal00 The extension uses `xdg-open` to open folders, apparently other Ubuntu users have encountered this problem. From an [Ask Ubuntu question](https://askubuntu.com/a/455691/115115):

> I had this problem on 14.04 using the gnome-session-fallback desktop. After trying the other solutions (removing MimeType=inode/directory; and editing /usr/share/applications/mimeinfo.cache) what actually fixed the problem was to run this command as your user:
> 
> `xdg-mime default nautilus.desktop  inode/directory`
>
> By default it is set to use nautilus-folder-handler.desktop, which for some reason ends up launching the dreaded baobab.
>
> answered by [richq](https://askubuntu.com/users/932/richq)

Let me know if that fixes your problem.

**Comment by andyholmes** [comment]
I've just tested a nightly of Ubuntu 17.10 and this bug still exists, apparently the above fix does not solve it. I'm re-opening it even though it's an upstream bug.

**Comment by andyholmes** [comment]
And I'm going to go ahead and close this one too, since there's not much I can do about it.
