### ISSUE TITLE
Add tooltips to images

### ISSUE THREAD

**Issue by bil-elmoussaoui** [andyholmes/gnome-shell-extension-mconnect#18]
I think you should add some tooltips to every Gtk Image. As it's not really clear what each image button does :)

**Comment by andyholmes** [comment]
In regards to device menu buttons, such as here: 

![device-menu](https://user-images.githubusercontent.com/1265208/29294536-b01865e0-8104-11e7-89df-a04d0a603e29.png)

There aren't actually tooltips in the [St](https://developer.gnome.org/st/3.24/)/Shell Toolkit, although their are some extensions that build custom ones. Any thoughts?

In regards to GtkImages in sms.js, [bug #780938](https://bugzilla.gnome.org/show_bug.cgi?id=780938) still affects currently deployed Gtk.

**Comment by bil-elmoussaoui** [comment]
@andyholmes It shouldn't be a problem. You can use colors variables from the themes. Or themes could add specific support for the extension. Or a better way to handle this instead of having an indicator per device :/ (It doesn't work as expected anyway, i will open the other issue about that)

**Comment by andyholmes** [comment]
Since you've opened this bug I hope you might lend a hand. I've adapted code from [applications-overview-tooltip](https://github.com/RaphaelRochet/applications-overview-tooltip) into a class, but for the life of me I can't get it to show on top of a popup menu.


[tooltip.txt](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1229829/tooltip.txt)

**Comment by bil-elmoussaoui** [comment]
I will take a look as soon as i can. I think, that otherwise, you can use a better UI with someting like this in the main popup menu (the one that contains wifi, sound & bluetoth).
- DEVICE 1 : 
   - Send a message
   - Locate
   - Open in Nautilus .....
DEVICE 2:
   - Send pair request
....
Ofc the actions should be hidden at first.
I can draw a mockup or even write the code if you think it's might be a better alternative to the current UI

**Comment by andyholmes** [comment]
One thing I was considering was an optional 'tooltip label' right beneath the buttons that would display different text depending on which button was being hovered, although one reason I went for icons was to reduce the amount of translations necessary.

**Comment by andyholmes** [comment]
@bil-elmoussaoui I think I got this now, I'll push some a code in a little bit.
