### ISSUE TITLE
Kde connect backend doesn't auto remove devices

### ISSUE THREAD

**Issue by bil-elmoussaoui** [andyholmes/gnome-shell-extension-mconnect#21]
I'm having an issue with some devices; I have tried to connect the same device using mconnect backend and then KDE connect backend. Which resulted in 4 devices. The 3 out of 4 are marked as "OFFLINE".

As you can see from D-Feet. I have 4 devices while I only have one
![screenshot from 2017-08-15 02-18-41](https://user-images.githubusercontent.com/7660997/29297275-1fe3e60a-8160-11e7-8bd5-3e739d78dfe3.png)

I think, that the user should be able to remove the devices or at least untrust, or unpair. It seems that there's an unpair DBus method.
When I enable showing unpaired & offline devices I'm getting this
![screenshot from 2017-08-15 02-21-40](https://user-images.githubusercontent.com/7660997/29297327-7bf39878-8160-11e7-86bc-f2c39ddea930.png)

I would love to remove those devices. I tried to execute the unpair DBus method but that didn't result in anything, the devices are still there and I still see those 4 offline/untrusted phones...

**Comment by andyholmes** [comment]
It's true there's no way in the extension unpair with devices. I'd like to fix that, but also keep the device menu as simple as possible. I reason that since it's possible in KDE Connect settings, that it's not urgent though.

Are you saying when you call 'unpair()' vias DBus that KDE Connect is still not removing them? As far as I know KDE Connect unpairing does work, I think I've tested it. I believe that KDE Connect keeps a cache file somewhere, it's possible that's not being updated.

**Comment by bil-elmoussaoui** [comment]
@andyholmes I don't think that unpairing/removing devices should add the extension/device menu. Adding that to the extension setting should be easier to handle :)

**Comment by bil-elmoussaoui** [comment]
@andyholmes I fixed the problem by running `kdeconnect-cli --refresh` + I have removed the unneeded device's folders under `$HOME/.config/kdeconnect/`

**Comment by andyholmes** [comment]
@bil-elmoussaoui I agree, unpairing is less common task and probably doesn't need to be prominent.

The extension preferences widget is pretty self contained, so it should be easy with GtkStackSwitcher to make a more complete settings app without affecting what's already there. One day I hope MConnect is more complete, so I'd like to keep hiding the backend service from the user, whenever possible.

wrt the kdeconnect cache, was removing the files necessary to completely remove them? If all that needs to happen is to call `kdeconnect-cli --refresh` maybe that should be a part of kdeconnect.js->Device.unpair()

**Comment by bil-elmoussaoui** [comment]
@andyholmes Honestly, i didn't debug that. So i don't know which step fixed it. I will try to unpair my phone and see if i can reproduce that again (with better steps this time :P)
