### ISSUE TITLE
Integrate SMS reply with GNOME shell

### ISSUE THREAD

**Issue by psukys** [andyholmes/gnome-shell-extension-mconnect#24]
Currently, when receiving an SMS, *reply* button forwards to kde connect SMS gui for interacting. A nice GNOME shell integration would be to integrate so that a response to SMS could be written in the same notification.

For reference of how this looks, [this plugin (even though not maintained anymore)](https://github.com/kagesenshi/gnome-shell-extensions-pidgin) integrated Pidgin with GNOME shell.

**Comment by andyholmes** [comment]
Currently receiving SMS is handled internally by KDE Connect, which [according to the source code](https://github.com/KDE/kdeconnect-kde/blob/5f0173f4699d120a065e9cd7ce72d4a4860a5bc4/plugins/telephony/telephonyplugin.cpp#L49-L60) should already pass incoming SMS to the telepathy framework, only falling back to notifications if that fails. Although Gnome Shell [includes a telepathy client](https://github.com/GNOME/gnome-shell/blob/master/js/ui/components/telepathyClient.js), this doesn't seem to work (at least for me).

Unfortunately, there is no way to distinguish the difference between regular notifications and SMS notifications via the DBus interface, except by reading the `internalId` and `ticker` properties, searching for known app-id's (eg. com.google.android.apps.messaging but could be many other to search for) and hoping the `ticker` property contains the phone number. Even if contacts are integrated, and the incoming sender's name is an _exact match_, there is no way to know you are replying to the same number they sent the text from and not another phone (eg, home/work/fax) number in their contacts.

![sms-dfeet](https://user-images.githubusercontent.com/1265208/29489777-7a307850-84dd-11e7-9807-32a53c16fce1.png)

You can try [filing a bug](https://bugs.kde.org/buglist.cgi?quicksearch=kdeconnect&list_id=1459134) for a better DBus interface, or better Telepathy integration (which is what the above Pidgin plugin uses) upstream, but from my side there is not much I can do that isn't an ugly, unreliable hack :/ Currently,  the only telephony method available at all is `sendSms(String phoneNumber, String messageBody)`.

**Comment by andyholmes** [comment]
I've expanded on this is the Wiki, so I'm going to close this now:

https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/SMS
