### ISSUE TITLE
Allow drag & drop for files

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-mconnect#29]
Proposed workflow: Select a file (or URL, see https://github.com/andyholmes/gnome-shell-extension-mconnect/issues/28) and move it to the indicator icon. The UI should change to show it accepts the file.
Then you can drop it and it is just sent.

**Comment by andyholmes** [comment]
I'll have a look into this when I can, but I'm not sure if Drag & Drop between Gtk applications (eg. Nautilus) and Shell is possible, with the exception of windows which already have a Shell presence/corresponding ClutterActor. If you know of any examples, that would help.

**Comment by rugk** [comment]
> Gtk applications (eg. Nautilus) and Shell

At least for the desktop it works…

**Comment by andyholmes** [comment]
Can you give me a specific example?

**Comment by rugk** [comment]
When you drop desktop files (`/usr/share/applications`) to the desktop (of course, when having desktop icons enabled), it works.

**Comment by andyholmes** [comment]
I believe that desktop icons are provided *by* Nautilus, ie. some sort of Nautilus window or widget is overlaid on the desktop, allowing drag and drop. Looking at the [dnd.js](https://github.com/GNOME/gnome-shell/blob/033277b68f2910e54ce62f45fa92af2f5092a7ba/js/ui/dnd.js) and [xdndHandler.js](https://github.com/GNOME/gnome-shell/blob/033277b68f2910e54ce62f45fa92af2f5092a7ba/js/ui/xdndHandler.js) source code for Gnome Shell, this doesn't seem to be possible. I'll leave the issue open in case anyone knows a way around this.

**Comment by andyholmes** [comment]
Since no one has jumped in to offer a solution and I haven't found any other working examples, I'm going to close this for now.
