### ISSUE TITLE
Unable to Open SMS Dialog window

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [andyholmes/gnome-shell-extension-mconnect#3]
I've just installed the v2 from releases and when i try to open the SMS dialog window it simply doesn't show up.

I'm on Pop_OS (which is almost the same thing as Ubuntu 17.10) using GNOME 24. I'm also using KDEConnect and the pairing/file sharing/etc. works just fine.

When I open `journalctl -f` and try to open the dialog window I get this:

```
ago 10 14:47:03 pop-os gjs[3410]: JS ERROR: TypeError: this._window is undefined
                                  Application<.vfunc_activate@/home/ricardo/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/sms.js:575:9
                                  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                  @/home/ricardo/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/sms.js:583:2
```

Hope it helps fixing the issue.

**Comment by tony5** [comment]
I have noticed this same issue when using GOA with gmail although I have not verified the error you described.
if I remove gmail GOA it will work.
also the application icon does not show.

**Comment by andyholmes** [comment]
Confirmed, that was a bad commit on my part. I've just pushed a commit that should fix the window dialog not showing as well as skip loading Google Contacts if there's a problem with the Goa account.

The issues here just exploded once my extension was finally approved, I'll try and upload a new release for you all to test in about an hour from now with a bunch of fixes, stay tuned.

**Comment by andyholmes** [comment]
New release v3 uploaded, let me know how it goes.

**Comment by andyholmes** [comment]
v4 is now available with some more work on this issue. Additionally be sure to install GIR for both Gnome Online Accounts and GData. On Ubuntu these are called "gir1.2-goa-1.0" and "gir-gdata-0.0".

**Comment by andyholmes** [comment]
This has been reported [fixed in v5](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/tag/v5).

**Comment by RicardoEPRodrigues** [comment]
Just a small correction, it's `gir1.2-gdata-0.0`.

Run `sudo apt install gir1.2-goa-1.0  gir1.2-gdata-0.0` and that should do it :smile:

**Comment by andyholmes** [comment]
@RicardoEPRodrigues ah thank you, I actually copy/pasted that from the README which should be updated.
