### ISSUE TITLE
Support mouse moving

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-mconnect#30]
Upstream [has problems](https://bugs.kde.org/show_bug.cgi?id=380078) with Wayland currently, so one cannot move the mouse when trying to remote control it via the phone.
I can click and use keyboard input, but moving the cursor does not work.

Can you do anything about it? As the extension is tightly integrated into GNOME, maybe it can make it possible?

**Comment by andyholmes** [comment]
Sorry, this plugin is handled internally and not exposed over DBus, so I can't do anything about it. I have no idea if KDE plans to support wayland, but this may be why KDE Connect doesn't.

**Comment by rugk** [comment]
Okay, opened bug on the "other" upstream: https://github.com/bboozzoo/mconnect/issues/14
