### ISSUE TITLE
Add disconnect button

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-mconnect#32]
Preferably from the menu. There should be a button to allow me from the desktop/extension to disconnect a device.

**Comment by andyholmes** [comment]
Do you mean "unpair"? "Connected" actually means "reachable", which is what KDE Connect calls it, and there is no way to control that, outside of turning the device's Wi-Fi off.

**Comment by rugk** [comment]
Not unpair in the sense that you cannot connect to the device afterwards. In the app the option is just called "close connection" (or so). So just close the connection.

**Comment by andyholmes** [comment]
@rugk There is no such function in the KDE Connect code, but definitely not in the DBus interface.

**Comment by rugk** [comment]
Sure, I know what to do…

Upstream 1: https://bugs.kde.org/show_bug.cgi?id=383821
Upstream 2: https://github.com/bboozzoo/mconnect/issues/16
