### ISSUE TITLE
device-link-symbolic looks blurry

### ISSUE THREAD

**Issue by bil-elmoussaoui** [andyholmes/gnome-shell-extension-mconnect#37]
The icons look blurry
![screenshot from 2017-08-24 02-34-25](https://user-images.githubusercontent.com/7660997/29644223-c155b03e-8874-11e7-946d-240730e36f62.png)

**Comment by andyholmes** [comment]
@bil-elmoussaoui the part of the SVG that's important here is (I think):

> \<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">

This icon's from Google's Material project, but I notice Numix doesn't use `height`/`width` in it's SVGs, just `viewBox`. I assumed Gtk/Gnome would change these parameters by itself if needed, but maybe not. Unfortunately the SVG is compiled into GResource so I can't really get you to play with it yourself without building from git.

It might just be how the icon looks, but I really don't know anything about SVGs. Here's a build from git/master with only `viewBox` but it looks the same to me:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1247412/mconnect.andyholmes.github.io.zip)

**Comment by bil-elmoussaoui** [comment]
Hey, don't worry about me I can build from git :)
I think the icon looks blurry because it's not pretty well designed (i know nothing about design guidelines :p) but I know how Inkscape works and having width/height and viewBox or just one of them won't change anything at least what I have tried recently using Gtk/Qt

**Comment by andyholmes** [comment]
Yeah, it's not a very icon in general, but it a was a quick fix at the time. Lately I've just been trying to figure out Vala and mconnect so I can get that working and turf KDE Connect, but I'd like to fix that whole icon business eventually.

**Comment by bil-elmoussaoui** [comment]
Well, let's hope some good designer will step up and fix those alignments issues. Or just create better ones

**Comment by HEXcube** [comment]
I can try aligning the pixels if you specify the svg file and the size needed

**Comment by bil-elmoussaoui** [comment]
Here you go https://github.com/andyholmes/gnome-shell-extension-mconnect/blob/master/data/device-link-symbolic.svg
It's a symbolic icon so i think only one size is needed

**Comment by HEXcube** [comment]
When I checked, the icon seems to be already aligned! See:

![aligned to grid](https://user-images.githubusercontent.com/3755396/30243224-d00c8dae-95c2-11e7-856d-21cdc2f55b91.png)

Could it be that GNOME's panel icons are 16x16 or 20x20 and not 24x24? :confused:

**Comment by andyholmes** [comment]
I think by default they are 16x16, but Gnome should be able to resize them if necessary. According to [this website](https://tagliala.github.io/vectoriconsroundup/) Material icons are "pixel perfect" at 24px, though.

**Comment by HEXcube** [comment]
> I think by default they are 16x16, but Gnome should be able to resize them if necessary.

The thing with vector icons is: upscaling works, but downscaling, not so much. When I checked, Numix and Adwaita symbolic icons are 16x16. So, I guess that's the size we need to target.

> According to this website Material icons are "pixel perfect" at 24px, though

When I checked [Material Icons](https://material.io/icons/#ic_devices), there's a 18x18 svg too. However, it's not fully aligned. I can modify it a bit and make it 16x16. By the way, thanks for that website link - [VectorIconsRoundup](https://tagliala.github.io/vectoriconsroundup/). Would come in handy for comparing icon fonts. :relaxed:

**Comment by HEXcube** [comment]
The 18x18 turned out to be just the 24x24 icon with a rescale. So, I modified the 24x24 icon, aligned the pixels and made it 16x16 :relaxed:

**Comment by andyholmes** [comment]
Wow, that's a lot clearer, well done!

![screenshot from 2017-09-10 13-39-48](https://user-images.githubusercontent.com/1265208/30252818-f047a174-962d-11e7-90f6-57f58fe01e7c.png)

I feel like it might be a little thin compared to other symbolic icons, though. What do you think?

**Comment by HEXcube** [comment]
> I took what you did and thickened it up a bit, what do you think of this?

Looks better! :+1: 

When I downscaled the icon to 16x16, the bezels were around 1.5px thick. So, I reduced them to 1px. Now u changed them to the more appropriate 2px size :relaxed:

**Comment by andyholmes** [comment]
Yeah, I see what you mean about the alignment, I tried 1.5px as well and it came out blurry like before. I'll push this in the next release but here's a build with it now:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1293995/mconnect.andyholmes.github.io.zip)

**Comment by HEXcube** [comment]
Yeah, half pixels are the culprits behind blurry icons. The key to getting crispy pixel perfect icons is to get them aligned to full pixels :relaxed:

**Comment by HEXcube** [comment]
> I'll push this in the next release but here's a build with it now:

Thanx for the intermediate build! :relaxed:  The icon now looks crispy clear

Before:
![before](https://user-images.githubusercontent.com/3755396/30339606-31e0a14a-980d-11e7-84f8-d02323dd5656.png)

After:
![after](https://user-images.githubusercontent.com/3755396/30339610-36eb7250-980d-11e7-9483-b2fc0e9dfa4c.png)

Don't mind the icon in menu, it's my Adapta shell theme's fault. :disappointed:  Adapta uses another icon size in menu (atleast on my GNOME 3.20). Don't know if it's fixed for new GNOME versions. Anyway, it looks fine under Adwaita:

![adwaita](https://user-images.githubusercontent.com/3755396/30339873-1cb88b88-980e-11e7-87c0-e0c7bd59b430.png)

**Comment by andyholmes** [comment]
That's annoying when you like a theme but it's just off a little bit. Since you pointed out the alignment I've been going through the rest of the material icons and fixing them, thanks for pointing that out.
