### ISSUE TITLE
Devices aren't visible on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by odifek** [andyholmes/gnome-shell-extension-mconnect#38]
I use Ubuntu 16.04 Gnome
It just continues scanning without end. even though the kdeconnect is connected and working.
![screenshot from 2017-09-01 08-29-31](https://user-images.githubusercontent.com/11685890/29959648-31dea5d2-8ef0-11e7-81fa-e28bc4996d72.png)
![screenshot from 2017-09-01 08-31-51](https://user-images.githubusercontent.com/11685890/29959647-31dc1d08-8ef0-11e7-83c2-2be52005a0bd.png)

**Comment by andyholmes** [comment]
@odifek From your Gnome Shell screenshot it's hard to tell for sure, in *Mobile Settings* do you have *Device Indicators* enabled or disabled? See [Device Indicators](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Preferences#device-indicators) in the wiki. From the KDE Connect screenshot, the phone "Ugo" should be showing, either in the status tray or in the User Menu.

Currently the scanning in the User Menu will continue forever until you click *Stop scanning for Devices*. The next release includes a timeout of 15 seconds.

**Comment by odifek** [comment]
It's enabled but I can't find the phone indicator on the menu
![screenshot from 2017-09-01 12-40-38](https://user-images.githubusercontent.com/11685890/29968331-166a029c-8f13-11e7-8161-2b5ba2de3d45.png)

**Comment by andyholmes** [comment]
Could you please open a terminal (Press Ctrl+Alt+T) and run this command:

> $ journalctl /usr/bin/gnome-shell -f -o cat

And then restart the extension, or restart Gnome Shell (Press Alt+F2 then input the letter 'r' and press enter). Then see if there are any errors related to mconnect?

**Comment by odifek** [comment]
No error whatsoever!

**Comment by andyholmes** [comment]
Could you run this in a terminal:

> $ kdeconnect-cli --version

It seems like kdeconnect in Ubuntu 16.04 is [version 0.8](https://packages.ubuntu.com/xenial/kdeconnect). If the version that prints out is less than **1.0**, you can setup up a new PPA in the terminal by running:

> sudo add-apt-repository ppa:varlesh-l/indicator-kdeconnect
> sudo apt-get update
> sudo apt-get upgrade

**Comment by odifek** [comment]
Updated to version 1.0, yet not working

**Comment by andyholmes** [comment]
Can you try stopping kdeconnect with the command:

> killall -15 kdeconnectd

Then restarting it in the User Menu by clicking *Enable*:

![Enable](https://github.com/andyholmes/gnome-shell-extension-mconnect/raw/master/extra/device-user-menu-enable.png)

**Comment by odifek** [comment]
Done. But no difference.
Maybe there is a conflict somewhere. I suppose.
Also after updating both system and phone app, remote mouse and keyboard
doesn't work anymore. Huh!

**Comment by odifek** [comment]
Just funny stuff. Remote input working again. Mconnect extension not yet
working

**Comment by andyholmes** [comment]
You can try restarting Gnome Shell once more with:

> $ journalctl /usr/bin/gnome-shell -f -o cat

running in a terminal. Without an error or an obvious version incompatibility, it's hard for me to find the problem.

**Comment by andyholmes** [comment]
@odifek I forgot to mention that if you enable *Debug mode* in preferences you may get more messages for the extension. Any errors should print anyways though.

**Comment by odifek** [comment]
No errors.
Are there other system dependencies that might affect it? Have not updated
my system for sometime now. Maybe it will work after full upgrade.
Will update you when I do that. As I don't have adequate internet access
now.
Thank you.

**Comment by andyholmes** [comment]
There shouldn't be any other dependencies required. Another user reported a similar error on [extensions.gnome.org](https://extensions.gnome.org/extension/1272/mconnect/) (unless you are also *falin.kv*). 

If you disable *Device Indicators* in the preferences, do the devices show in the User Menu?

**Comment by odifek** [comment]
Okay. I am not the other person.
No, only the menu item that displays settings and stop scanning for
devices.

**Comment by andyholmes** [comment]
This might be a long shot, but could you install this ZIP using Gnome Tweak, then restart Gnome Shell:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1271464/mconnect.andyholmes.github.io.zip)

**Comment by odifek** [comment]
Have done that but no positive result however

**Comment by andyholmes** [comment]
Sorry to hear that didn't help, without any errors, warnings or other messages it's almost impossible for me to track this problem down.

**Comment by odifek** [comment]
Wow! Finally this worked! Thank you very much!
So, is this one an older version or something?

**Comment by andyholmes** [comment]
The version I sent you is exactly the same as the one on extensions.gnome.org (v11) just with that one fix. Thanks for working through this with me, now I can push a new version to the website.

**Comment by odifek** [comment]
I appreciate your patience also. Thanks

**Comment by HEXcube** [comment]
Thanks for fixing this bug! :relaxed: I was stuck on v8 of the extension for a month. Now, I've finally upgraded to v13 on my Ubuntu GNOME 16.04LTS (with GNOME 3.20 upgrade) and it works fine again.
