### ISSUE TITLE
Gnome Shell 3.25/3.26 not tested

### ISSUE THREAD

**Issue by kubwit** [andyholmes/gnome-shell-extension-mconnect#40]
i'm on 16.04 with gnome-shell updated yesterday and i'm unable to install it. when i go on the extensions site i click the button to turn it on the pop up for the install appears. i click ok , the popup disappears and the button on/off moves slowly to off. i'm on firefox 55

**Comment by andyholmes** [comment]
@kubwit, that is strange. I've had some problems with 16.04 users, but the version on extensions.gnome.org is actually an older version (v12) that I released to fix Ubuntu 16.04.

You could install v13 just released yesterday by downloading from [here](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/download/v13/mconnect.andyholmes.github.io.zip) and install it in Gnome Tweak. It takes a bit of time before they review new releases for the website.

If that doesn't help, run these commands in a terminal and let me know what they say:

> $ gjs --version
> $ gnome-shell --version

**Comment by kubwit** [comment]
Thanks for reply... I think it was a firewall problem...I don't have the
terminal reachable. Ubuntu 17.10? Did you try to install... I wasn't able
to.

Il 06 set 2017 20:54, "Andy Holmes" <notifications@github.com> ha scritto:

**Comment by andyholmes** [comment]
You should be able to run a terminal with Ctrl+Alt+T or Alt+F2 then run `gnome-terminal`.

I haven't yet tested for Ubuntu 17.10, in order to make it work each version of Gnome Shell has to be added to `metadata.json` before it will even *try* to work. If you'd like to try you can add the version printed out by `gnome-shell --version`  and add it to the file 

> ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/metadata.json

I haven't had a chance to test on the latest Gnome Shell, mostly because it is still in development and even the version number will change quite often. I think right now it is `3.25.91`, but that might have changed already.

**Comment by kubwit** [comment]
Little feedback.
Copied manually v13 in .local extensionsdirectory. restarted and it doesn't appear in ubuntu beta 17.10. (with modified json)

I enabled it over the extension website where it was able to enable it after manual installation. Later i try in wifi envirement so i can tell you if it's working with 17.10

**Comment by kubwit** [comment]
ok. so i tried in my lan enviroment it does not work in 17.10 installed and up to date to day. The gnome shell version is GNOME Shell 3.25.91 and i'm on 17.10. same Lan same machine i have double boot kde-neon 5.10.5 it works there. No firewall is enabled on gnome shell. When you like i can make some test for you just give me advice when you are comfortable

**Comment by kubwit** [comment]
gjs 1.49.92

**Comment by andyholmes** [comment]
Here's a test build with an updated metadata.json and some fixes for newer GJS that may help. See [Debugging](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Debugging) in the wiki to get some useful output:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1285867/mconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
I've just release [v14](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/tag/v14) which includes the above fixes and version in `metadata.json`, give it a try if you like.

**Comment by andyholmes** [comment]
After some snooping around it seems like most extensions support Gnome Shell 3.26 are adding "3.26" not "3.25.91" to their metadata.json files. Maybe try that and let me know.

**Comment by andyholmes** [comment]
I'm marking this as closed, since the extension seems work well for me in latest nightlies.
