### ISSUE TITLE
Unable to make Contacts Auto-Complete works

### ISSUE THREAD

**Issue by SimonMellerin** [andyholmes/gnome-shell-extension-mconnect#44]
I have my contacts synchronized with Nextcloud, they appear in my gnome contact app.

All I need is to install folks and they will be found by mconnect ?

**Comment by andyholmes** [comment]
@SimonMellerin If they are showing in Gnome Contacts, then the only other thing you should have to install is the Folks GIR. On Ubuntu this package is called `gir1.2-folks-0.6`. NextCloud was the service provider that this feature was tested with, so it should work!

**Comment by SimonMellerin** [comment]
Well it doesn't :/
Is there an option to put on in mconnect-extension or in KDE Connect settings ?

When I open the window to write a new sms, in the textbox, it only says 'Type a number'

Thanks

**Comment by andyholmes** [comment]
No, it's actually all automatic, if Folks and the GIR is installed it should just work automatically. For some technical reasons it uses a Python script to query folks, could you try running this in a terminal and tell me what it says or if there are any errors:

> $ python3  ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/folks.py

This should print a list of all your contacts.

**Comment by SimonMellerin** [comment]
Ok,  it seems my system can't find libgobject-2.0.so

`python3 ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/folks.py
Traceback (most recent call last):
  File "/home/simon/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/folks.py", line 9, in <module>
    pyc.cdll.LoadLibrary('libgobject-2.0.so')
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgobject-2.0.so: cannot open shared object file: No such file or directory`

**Comment by andyholmes** [comment]
Golly, that's surprising. Oops, maybe not. Apparently that is a part of `libglib2.0-dev` (at least on Ubuntu). It must be an odd requirement of `folks.py` because of the C->Python mapping it does to make libgee work.

**Comment by SimonMellerin** [comment]
Yep, it works after I've installed _libglib2.0-dev_ 

thanks !

**Comment by andyholmes** [comment]
Glad to hear it!
