### ISSUE TITLE
ServiceUnknown: The name org.mconnect was not provided by any .service files

### ISSUE THREAD

**Issue by hackel** [andyholmes/gnome-shell-extension-mconnect#45]
I first installed v12 from extensions.gnome.org.  It didn't show any indicator icon, but I could open the configuration options and select the mconnect backend, which I have set up and is paired and working properly.  I do receive notifications on my desktop from my mobile.

Then I installed the v13 release from here.  I still don't get a menu icon, and now when I try to open the extension settings, I get:
```
Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.mconnect was not provided by any .service files

Stack trace:  ProxyBase<._call@mconnect.js:168:19
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  DeviceManager<._init@mconnect.js:474:9
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  KeybindingProfileBox<._init@prefs.js:406:28
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  KeybindingWidget<._init@prefs.js:667:23
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  buildPrefsWidget@prefs.js:1037:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:49
```

**Comment by andyholmes** [comment]
Not being able to open the preferences when the selected service is not running is a bug I became aware of just yesterday, here is a build which should fix that:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1285802/mconnect.andyholmes.github.io.zip)

Are you sure you have MConnect running though, and not KDE Connect? As I recall MConnect will not automatically start and must be started manually or setup to run at startup.

**Comment by andyholmes** [comment]
I've just release [v14](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/tag/v14) which includes the fix for the Preferences bug.

Additionally, it occurs to me that you may be getting the above error if you haven't built MConnect from the dbus-support branch. I have some instructions in the wiki for [installing MConnect](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Installation#mconnect) from that branch that may help.

**Comment by andyholmes** [comment]
The dbus-support branch has been merged into master and I've updated the [build instructions](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Installation#mconnect) in the Wiki.

**Comment by andyholmes** [comment]
Marking this as closed, since dbus-support has been merged and seems to work well.
