### ISSUE TITLE
Can't remove "Mobile Devices" from Gnome-Shell menu

### ISSUE THREAD

**Issue by stefaca** [andyholmes/gnome-shell-extension-mconnect#49]
I tried to install this extension, something failed but in menu now I have Mobile Devices part. How can I remove that? 

Read in Wiki that this is a part of extension but I want to remove it. 

Image: https://github.com/andyholmes/gnome-shell-extension-mconnect/raw/master/extra/device-user-menu-enable.png

**Comment by andyholmes** [comment]
Sorry to hear it didn't work out for you. You can uninstall extensions on the extension website [right here](https://extensions.gnome.org/local/).

**Comment by stefaca** [comment]
I don't know why that issue is happening. GNOME Shell 3.22.3, Debian. I was looking at `/usr/share/gnome-shell/extensions/` and `.local/share/gnome-shell/extensions/` and there is no extension. So, extension is removed but part in menu was still visible.

**Comment by andyholmes** [comment]
That is weird, I just tested uninstalling and it worked for me, but I'm on 3.24. Maybe an old bug in 3.22?

**Comment by stefaca** [comment]
Maybe, Debian although it is on testing branch, has a little bit older packages. Who knows :) I did a quick system restore (I'm doing a periodical system backup). 

If you agree we can close this one?

**Comment by andyholmes** [comment]
Sure, thanks for letting me know anyways, in case anyone else has this issue.
