### ISSUE TITLE
Can't Hide Unpaired Devices

### ISSUE THREAD

**Issue by isantop** [andyholmes/gnome-shell-extension-mconnect#6]
In the settings, I tried to uncheck the visibility option for unpaired devices. However, there is still an unpaired device on the panel. Additionally, if I close and reopen the settings, the box for unpaired devices is re-checked.

**Comment by andyholmes** [comment]
@isantop confirmed and fix pushed, stay tuned for a new release on Github within the hour

**Comment by andyholmes** [comment]
New release v3 uploaded, let me know how it goes.

**Comment by andyholmes** [comment]
Fixed in v3
