### ISSUE TITLE
Can't click on icon on indicator

### ISSUE THREAD

**Issue by yodatak** [andyholmes/gnome-shell-extension-mconnect#61]
I can't click on the icon , but the batery indicator is correct 

![capture d ecran de 2017-09-19 13-47-22](https://user-images.githubusercontent.com/704477/30591111-da72ab6c-9d41-11e7-9112-10ff7f70f7bf.png)

**Comment by andyholmes** [comment]
You mean click on the battery icon?

**Comment by yodatak** [comment]
Oh ok , i use mconnect service and they don't support it so its normal ^^ Thanks for this sorry about this issue , is its writen in the readme.md ?

**Comment by andyholmes** [comment]
It's in the Wiki installation page under [MConnect](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Installation#mconnect), but that's okay. Right now the developer of MConnect is working on implementing TLS sockets for to get the protocol up to date from 5->7, probably more plugins will be easier after that is done. I think he said he's quite busy with other projects so if you know anyone with Vala experience you should encourage them to help him out.
