### ISSUE TITLE
Support KDE Connect version 1.2

### ISSUE THREAD

**Issue by egrechko** [andyholmes/gnome-shell-extension-mconnect#72]
Hello,

I am currently having a problem setting up my phone with the mconnect extension. I installed kde connect with all of the kde dependecies. I set up / paired my device with kde connect and installed the extension. The device shows up as paired in kde connect but when i look at the extension it shows up as red and says that the device is not connected. What can i do to fix the problem. Did i set up the extension wrong? I first got the extension from gnome-extensions and that didn't work. I then (currently) installed it from source through the git repo and that also does not work. 

I have attached screen shots as well maybe they will help. 

Any information will be much appreciated. 
Eugene.

![kdeconnect-working](https://user-images.githubusercontent.com/15573354/31907465-bb73a088-b7e8-11e7-8b9c-eba4f2afc0fc.png)
![mconnect-not-working](https://user-images.githubusercontent.com/15573354/31907466-bb8ebdb4-b7e8-11e7-8369-7f6f54faa91e.png)

**Comment by egrechko** [comment]
I forgot to mention that notifications are also working. Here is a screen shot. 
I am running gnome version 3.18

![notifications are working](https://user-images.githubusercontent.com/15573354/31907824-d2765964-b7e9-11e7-82e7-cbe173ce2527.png)

**Comment by andyholmes** [comment]
I recall there was a similar issue sometime ago, (Issue #34) where someone was using an Arch based distro using a version of KDE Connect built from upstream Git. Is this the case for you? Could you run this in a terminal for me:

`kdeconnect-cli --version`

Currently, I think the extension works with version 1.0  and I know there were some API breaks already in Git before 1.2 was released about a month ago. If you are using a version older than 1.0 you should upgrade using one of the PPA's available [here](https://launchpad.net/~webupd8team/+archive/ubuntu/indicator-kdeconnect) or [here](https://www.ubuntuupdates.org/pm/kdeconnect). If you're using a version from Git, I can't support that, but if you found a PPA for version 1.2 for Ubuntu I could test and support that.

**Comment by andyholmes** [comment]
I've had a quick look into this, and apparently this has changed in 1.2. I can try to support the new DBus interface but I won't be able to test it since it's not available on Ubuntu or Debian yet.

**Comment by andyholmes** [comment]
Should be fixed in [v17](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/tag/v17)

**Comment by egrechko** [comment]
Thank you for your support Andy. 

Adding the PPA and installing kdeconnect and indicator-kdeconnect fixed my problem. Everything works great now! For anyone reading this make sure you log out of gnome and log back in after installing kde connect to make sure everything works well.
