### ISSUE TITLE
Notification bar filled with lots of unwanted devices

### ISSUE THREAD

**Issue by vdmkenny** [andyholmes/gnome-shell-extension-mconnect#76]
Hi,

In my office, multiple people use KDE connect, so my notification bar is getting filled with red unpaired devices. Is there a way to hide unpaired devices from the top bar? 

If not, could a toggle be added for this?

**Comment by andyholmes** [comment]
This is possible in the extension preferences, see the [Device Visibility](https://github.com/andyholmes/gnome-shell-extension-mconnect/wiki/Preferences#device-visibility) option.
