### ISSUE TITLE
[Support Request] Is it possible to backport for GNOME Shell 3.18/3.20?

### ISSUE THREAD

**Issue by HEXcube** [andyholmes/gnome-shell-extension-mconnect#9]
I tried the extension on Ubuntu GNOME 16.04LTS with upgraded Shell 3.20 (default was 3.18). However, the extension didn't work.

![mconnect on shell 3 20](https://user-images.githubusercontent.com/3755396/29202522-ad141392-7e86-11e7-8183-26435565a31e.png)

I tried changing

```
"shell-version": [ "3.24", "3.24.1", "3.24.2" ],
```
to 

```
"shell-version": ["3.20", "3.24", "3.24.1", "3.24.2" ],
```
just to see if it'd work even though not explicitly supported. Unfortunately, it didn't. :disappointed: So, would it be possible to enable support for Shell 3.18 or 3.20?

**Comment by andyholmes** [comment]
Did you close Gnome Tweaks and restart Gnome Shell before retrying? If so, are there any errors in looking glass (Alt+F2 then "lg") that could give me a hint as to what's not compatible?

**Comment by HEXcube** [comment]
> Did you close Gnome Tweaks and restart Gnome Shell before retrying?

@andyholmes Yeah, I did. Both times, before editing metadata.json and after. After editing, it was possible to enable it via Tweaks but the indicator didn't show up at all. :worried:

I'll try Looking Glass now. Didn't know shell had a built in tool for debugging. :relaxed:

**Comment by HEXcube** [comment]
Unfortunately, I can't reproduce the working extension setup. :worried:  Now, after I edited `metadata.json` and declared Shell 3.20 support, Tweak just says "Error loading extension":

![mconnect extension not loaded](https://user-images.githubusercontent.com/3755396/29203329-bfc17e9c-7e8d-11e7-8073-2acacd2d47b9.png)

Inspection through Looking Glass didn't help either:

![mconnect looking glass](https://user-images.githubusercontent.com/3755396/29203337-d18eb2e8-7e8d-11e7-802f-14b8f22fae68.png)

I've kept the extension installed. Incase if I'm able to enable it later, I'll post the debugging results here.

**Comment by andyholmes** [comment]
Since the version of Ubuntu you're using is LTS I would be interested in supporting it if possible, but I don't have it available. Could you run 'gjs --version' in a terminal and report what it says?

Additionally, if you could run 'journalctl /usr/bin/gnome-shell -f -o cat' in a terminal and restart gnome shell to see if throws any errors or warnings that might give me a clue?

**Comment by HEXcube** [comment]
`gjs --version` isn't working. But it's `1.44.0-1ubuntu1` by default for Ubuntu 16.04LTS's Shell 3.18. I found out from https://launchpad.net/ubuntu/+source/gjs

However, since I've upgraded to Shell 3.20 from Staging PPA, it's `1.45.4-1~ubuntu16.04.1` for me now.

**Comment by HEXcube** [comment]
@andyholmes  I ran `journalctl /usr/bin/gnome-shell -f -o cat` and restarted shell. This is the error I got:

```
(gnome-shell:3411): Gjs-CRITICAL **: JS ERROR: Exception in callback for signal: extension-found: SyntaxError: identifier starts immediately after numeric literal @ /home/hexcube/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io/extension.js:550
```

**Comment by andyholmes** [comment]
@HEXcube I see, this is related to a change in javascript regarding octal numbers. Try to open up 'extension.js' and just delete that line, or alternatively comment it out with '//'.

If that's the only reason the extension won't work, there's good chance I can find another way to do that. However, that tells me your version of GJS conforms to an old standard of Javascript which *may* make the extension unusable with your version of Ubuntu.

**Comment by andyholmes** [comment]
Actually, scratch that, just replace 0o755 with 493.

**Comment by andyholmes** [comment]
This particular error has been [fixed in v5](https://github.com/andyholmes/gnome-shell-extension-mconnect/releases/tag/v5). Let me know if the extension works in 3.20 with just that fix.

**Comment by severin-lemaignan** [comment]
Tested v7 on gnome-shell 3.18 (ubuntu 16.04), works well.

**Comment by andyholmes** [comment]
@severin-lemaignan excellent, I will add 3.18 and 3.20 to supported versions

**Comment by HEXcube** [comment]
Sorry 4 the delay :sweat_smile: , but I was out of station for a few days. I tested the extension when I came back and now it works fine! :smiley: 

![popover menu](https://user-images.githubusercontent.com/3755396/29375410-87cee706-82d2-11e7-80ba-3d4d536b3163.png)
![system menu](https://user-images.githubusercontent.com/3755396/29375409-87c1cc06-82d2-11e7-9462-a2af7b087afa.png)

Thanx for backporting this really useful extension @andyholmes  :relaxed:

**Comment by andyholmes** [comment]
Glad to hear it, thanks for checking back!
